version: "3.9"

# Define services
services:
  # App Service
  app:
    # Configuration for building the docker image for the service
    container_name: dev-stella
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    env_file: # Pass environment variables to the service
      - ./.env
    depends_on:
      dev-postgres:
        condition: service_healthy
    networks:
      - backend
  dev-postgres:
    image: postgres:latest
    container_name: dev-postgres
    environment:
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge