// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	model "babalaas/stella-artois/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserProfileRepository is an autogenerated mock type for the UserProfileRepository type
type UserProfileRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userProfile
func (_m *UserProfileRepository) Create(ctx context.Context, userProfile *model.UserProfile) (uuid.UUID, error) {
	ret := _m.Called(ctx, userProfile)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) (uuid.UUID, error)); ok {
		return rf(ctx, userProfile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) uuid.UUID); ok {
		r0 = rf(ctx, userProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserProfile) error); ok {
		r1 = rf(ctx, userProfile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserProfileRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserProfileRepository creates a new instance of UserProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserProfileRepository(t mockConstructorTestingTNewUserProfileRepository) *UserProfileRepository {
	mock := &UserProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
