// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	model "babalaas/stella-artois/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserProfileService is an autogenerated mock type for the UserProfileService type
type UserProfileService struct {
	mock.Mock
}

// LogIn provides a mock function with given fields: ctx, userProfile
func (_m *UserProfileService) LogIn(ctx context.Context, userProfile *model.UserProfile) (model.UserProfile, error) {
	ret := _m.Called(ctx, userProfile)

	var r0 model.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) (model.UserProfile, error)); ok {
		return rf(ctx, userProfile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) model.UserProfile); ok {
		r0 = rf(ctx, userProfile)
	} else {
		r0 = ret.Get(0).(model.UserProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserProfile) error); ok {
		r1 = rf(ctx, userProfile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, userProfile
func (_m *UserProfileService) Register(ctx context.Context, userProfile *model.UserProfile) (model.UserProfile, error) {
	ret := _m.Called(ctx, userProfile)

	var r0 model.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) (model.UserProfile, error)); ok {
		return rf(ctx, userProfile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserProfile) model.UserProfile); ok {
		r0 = rf(ctx, userProfile)
	} else {
		r0 = ret.Get(0).(model.UserProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserProfile) error); ok {
		r1 = rf(ctx, userProfile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserProfileService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserProfileService creates a new instance of UserProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserProfileService(t mockConstructorTestingTNewUserProfileService) *UserProfileService {
	mock := &UserProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
